apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-9-deploy
  namespace: test
  labels:
    app: app-9-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-9-deploy
  template:
    metadata:
      labels:
        app: app-9-deploy
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: app-9
        image: app-9
        resources:
          requests:
            cpu: 1
            memory: 0.19Gi
            wh.com/bandwidth: 5Mi
            wh.com/disk: 8Gi
          limits:
            cpu: 2
            memory: 4Gi
            wh.com/bandwidth: 5Mi
            wh.com/disk: 8Gi
