apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: test
  labels:
    app: tomcat
spec:
  replicas: 8
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      hostNetwork: true
#      tolerations:
#      - key: node-role.kubernetes.io/master
#        operator: Exists
#        effect: NoSchedule
      # nodeSelector:
      #   node-role.kubernetes.io/xdragon: "true"
      containers:
      - name: tomcat
        image: tomcat
        resources:
          requests:
            cpu: 0.5
            memory: 0.5Gi
            wh.com/bandwidth: 20Mi
            wh.com/disk: 20Gi
          limits:
            cpu: 4
            memory: 8Gi
            wh.com/bandwidth: 20Mi
            wh.com/disk: 20Gi
