kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-yoda-snapshotter
  namespace: {{ .Values.yoda_namespace }}
  labels:
    app: csi-yoda-snapshotter
spec:
  selector:
    matchLabels:
      app: csi-yoda-snapshotter
{{- if .Values.globalconfig.SingleMasterMode }}
  replicas: 1
{{- else }}
  replicas: 2
{{- end }}
  template:
    metadata:
      labels:
        app: csi-yoda-snapshotter
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: csi-yoda-snapshotter
            topologyKey: kubernetes.io/hostname
      priorityClassName: system-node-critical
      serviceAccount: yoda
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: csi-snapshotter
          image: "{{ .Values.globalconfig.RegistryURL }}/{{ .Values.images.snapshotter.image }}:{{ .Values.images.snapshotter.tag }}"
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --snapshot-name-prefix=snap
            - --leader-election=true
            # no extra-create-metadata flag in v3.0.0
            # - --extra-create-metadata=true
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/yodaplugin.csi.alibabacloud.com/csi.sock
            - name: TZ
              value: Asia/Shanghai
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/yodaplugin.csi.alibabacloud.com
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/yodaplugin.csi.alibabacloud.com
            type: DirectoryOrCreate
