apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
  annotations:
    resize.oecp.io/enabled: "true"
  labels:
    trident-app: yoda
provisioner: yodaplugin.csi.alibabacloud.com
parameters:
  volumeType: "LVM"
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.mountpoint_hdd.name }}
  labels:
    trident-app: yoda
provisioner: yodaplugin.csi.alibabacloud.com
parameters:
  volumeType: MountPoint
  mediaType: hdd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.mountpoint_ssd.name }}
  labels:
    trident-app: yoda
provisioner: yodaplugin.csi.alibabacloud.com
parameters:
  volumeType: MountPoint
  mediaType: ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_hdd.name }}
  labels:
    trident-app: yoda
provisioner: yodaplugin.csi.alibabacloud.com
parameters:
  volumeType: Device
  mediaType: hdd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_ssd.name }}
  labels:
    trident-app: yoda
provisioner: yodaplugin.csi.alibabacloud.com
parameters:
  volumeType: Device
  mediaType: sdd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer