apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-deploy-02
  name: gpu-deploy-02
  namespace: pai-gpu
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gpu-deploy-02
  template:
    metadata:
      labels:
        app: gpu-deploy-02
    spec:
      containers:
      - image: tensorflow:latest
        name: main
        resources:
          limits:
            alibabacloud.com/gpu-mem: 10240Mi
            cpu: 12
            memory: 18432Mi
          requests:
            alibabacloud.com/gpu-mem: 10240Mi
            cpu: 12
            memory: 18432Mi
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
