apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-deploy-01
  name: gpu-deploy-01
  namespace: pai-gpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpu-deploy-01
  template:
    metadata:
      labels:
        app: gpu-deploy-01
    spec:
      containers:
      - image: tensorflow:latest
        name: main
        resources:
          limits:
            alibabacloud.com/gpu-mem: 2048Mi
            alibabacloud.com/gpu-count: 1
            cpu: 8
            memory: 17408Mi
          requests:
            alibabacloud.com/gpu-mem: 2048Mi
            alibabacloud.com/gpu-count: 1
            cpu: 8
            memory: 17408Mi
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
