apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
  labels:
    app: busybox-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: busybox-deploy
  template:
    metadata:
      labels:
        app: busybox-deploy
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      # nodeSelector:
      #   node-role.kubernetes.io/xdragon: "true"
      containers:
      - name: busybox
        image: busybox
        resources:
          requests:
            cpu: 1500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
