apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deploy
  namespace: test
  labels:
    app: app-2-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2-deploy
  template:
    metadata:
      labels:
        app: app-2-deploy
    spec:
      hostNetwork: true
#      tolerations:
#      - key: node-role.kubernetes.io/master
#        operator: Exists
#        effect: NoSchedule
      containers:
      - name: app-2
        image: app-2
        resources:
          requests:
            cpu: 100m
            memory: 350Mi
          limits:
            cpu: 500m
            memory: 1Gi
