apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemonset
  namespace: simple
  labels:
    app: busybox-daemonset
spec:
  selector:
    matchLabels:
      app: busybox-daemonset
  template:
    metadata:
      labels:
        app: busybox-daemonset
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      containers:
      - image: busybox
        name: busybox-daemonset
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 256Mi
      nodeSelector:
        beta.kubernetes.io/os: linux